config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#home'

  resources :profile

  resources :dress do 
    member do 
      post    :vote
      post    :favorite
      patch   :unfavorite  #FIXME patch instead of delete? actually...don't need route??
    end
  end

  scope :discussion do 
    resources :posts do
      resources :comments do
      end
    end
    get '/yelp' => 'posts#search', as: 'search_yelp'
  end

  resources :schedule
  resources :availabilities
  resources :budget , only: [:index, :create, :destroy]

  patch '/budget/update' => 'budget#update', as: 'udpate_budget'
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @availability = Availability.all
  end

  def show
  end

  def new
    @availability = Availability.new
  end

  def edit
  end

  def create
    @availability = Availability.new(a_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: 'Success created'}
        format.json { render :show, status: :created, location: @availability}
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
     respond_to do |format|
      if @availability.update(a_params)
        format.html { redirect_to @availability, notice: 'Successfully updated'}
        format.json { render :show, status: :ok, location: @availability}
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to schedule_index_path, notice: 'Deleted'}
      format.json { head :no_content }
    end
  end


  private
    def a_params
      params.require(:availability).permit(:name, :start_at)
    end

    def set_event
      @availability = Availability.find(params[:id])
    end
end

app/views/schedule/_form.html.erb
<div class="container">
  
<%= form_for(@availability) do |f| %>
  <% if @availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h2>
      <ul>
      <% @availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/schedule/edit.html.erb
<div class="container">
<h2>Make your edits below:</h2>

<%= render 'form' %>

<%= link_to 'Show', schedule_path(@availability) %>
<%= link_to 'Back', schedule_index_path %>
</div>

app/views/schedule/index.html.erb
<div class="container">
  <div class="schedule_wrap">
    <div class="row">
      <div class="col-md-8">
        <h2> When is everyone free? </h2>
      </div>
      <div class="col-md-4">
        <%= link_to new_schedule_path do %>
          <h2><i class="fa fa-calendar"></i> Mark the calendar!
        <% end %></h2>
      </div>
    </div>
<br>
    <div class="row">
      <div class="col-md-8">
        <%= month_calendar events: @availability, table: {class: "calendar table table-bordered"} do |date, available| %>
          <%= date.strftime("%d") %>
          <% if date == Date.today %>
            <strong>Today!</strong>
          <% end %>
          <% available.each do |a| %>
            <div><%= a.name %></div>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-4">
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Start time</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @availability.each do |a| %>
              <tr>
                <td><%= a.name %></td>
                <td><%= a.start_at %></td>
                <td><%= link_to schedule_path(a) do %>
                  <i class="fa fa-info"></i>
                <% end %></td>
                <td><%= link_to edit_schedule_path(a) do %>
                  <i class="fa fa-pencil"></i>
                <% end %></td>
                <td><%= link_to schedule_path(a), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash-o"></i>
                <% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/schedule/new.html.erb
<div class="container">
<h2>I am available on _ day, starting at _.</h2>

<%= render 'form' %>

<%= link_to 'Back', schedule_index_path %>
</div>

app/views/schedule/show.html.erb
<div class="container">
<h2>Check your availability below. Edit if necessary.</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @availability.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @availability.start_at %>
</p>

<%= link_to 'Edit', edit_schedule_path(@availability) %>
<%= link_to 'Add More', new_schedule_path %>
<%= link_to 'Return to Calendar', schedule_index_path %>
</div>