config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#home'

  resources :profile

  resources :dress do 
    member do 
      post    :vote
      post    :favorite
      patch   :unfavorite  #FIXME patch instead of delete? actually...don't need route??
    end
  end

  scope :discussion do 
    resources :posts do
      resources :comments do
      end
    end
    get '/yelp' => 'posts#search', as: 'search_yelp'
  end

  resources :schedule
  resources :availabilities
  resources :budget , only: [:index, :create, :destroy]

  patch '/budget/update' => 'budget#update', as: 'udpate_budget'
end

app/controllers/dress_controller.rb
class DressController < ApplicationController

  def index
    @dress = Dress.all
    favorites = Favorite.all
    @faves = favorites.map { |f| f.dress_id }
  end

  def new
    @dress = Dress.new
  end

  def create
    @dress = Dress.new(dress_params)
    if @dress.save
      redirect_to dress_path(@dress)
    else
      render :new
    end
  end

  def show
    @dress = Dress.find(params[:id])
  end

  def vote
    dress = Dress.find(params[:id])
    if current_user.vote_for dress
      flash[:notice] = "Your vote has been recorded!"
    else
      flash[:error] = "You are out of votes!"
    end
    redirect_to :back
  end

  def favorite
    dress = Dress.find(params[:id])
    if current_user.bride
      current_user.favorite dress
      redirect_to :back
      flash[:notice] = "This dress has been favorited!"
    end
  end

  def unfavorite
    dress = Dress.find(params[:id])
    if current_user.bride
      current_user.unfavorite dress
      flash[:notice] = "This dress has been UNfavorited!"
    else
      flash[:error] = "Only the bride is allowed to UNfavorite a dress."
    end
    redirect_to :back
  end

  private 
    def dress_params
      params.require(:dress).permit(:name, :image, :remote_image_url)
    end
end

app/views/dress/index.html.erb
<div class="dress_wrap">
  <div class="container">
    <div class="scroll-top lvm-state-hidden"><i></i>
    </div>  
            
    <% @dress.in_groups_of(3, false) do |dresses| %>
      <div class="row">
        <% dresses.each do |d| %>
          <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="card-image">
              <figure  style="height:420px; width:320px;" >            
                <img src="<%=d.image_url(:thumb)%>"  height="400"  width="320"  alt=""  style=" ">
              </figure>
            </div>
            <div class="container">
              <div class="col-sm-4">
                
                <p class="lead"><%= d.name %></p>  
                <div class="col-sm-4">
                <p><% if current_user %>
                    <%= button_to vote_dress_path(d), class: "btn btn-default" do %>
                      <i class="fa fa-thumbs-o-up"></i>
                    <% end %>
                  <% end %>
                </p></div>

                <div class="col-sm-4"><p><% if @faves.include? d.id %>
                    <%= button_to unfavorite_dress_path(d), method: :patch, class: "btn btn-default" do %>
                      <i class="fa fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= button_to favorite_dress_path(d), class: "btn btn-default" do %>
                      <i class="fa fa-heart-o"></i>
                    <% end %>
                  <% end %>
                </p></div>
                
                <div class="col-sm-3"><p># of Votes: <%= d.votes.count %></p></div>
              
              </div>
            </div>
          </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="col-sm-4">
      <div class="panel panel-default">
        <figure  style="height:420px; width:320px;" >
          <img src="/pikachu.jpg" height="300"  width="320"  alt=""  style=" ">
          <h3><%= link_to new_dress_path do %>
            <i class="fa fa-female"></i> Make a dress suggestion
          <% end %></h3>
        </figure>
      </div>
    </div>

  </div>
</div>

app/views/dress/new.html.erb
<div class="container">
<h2>Any Suggestions?</h2>

<%= form_for @dress, url: dress_index_path, :html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url %>
  </p>
  <p><%= f.submit "Upload Image"%></p>
<% end %>

<br>
<%= link_to "View Current Suggestions", dress_index_path %>

</div>

app/views/dress/show.html.erb
<div class="container">
    <h2></h2>
    <div class="col-md-4 col-md-offset-4">

    <h3><%= @dress.name %></h3><br>
    <%= image_tag @dress.image_url(:thumb).to_s %>

    <h3><%= link_to new_dress_path do %>
      <i class="fa fa-female"></i> Add another Dress
    <% end %></h3>

    <h3><%= link_to dress_index_path do %>
      <i class="fa fa-picture-o"></i> See current suggestions
    <% end %></h3>
  </div>
</div>