config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#home'

  resources :profile

  resources :dress do 
    member do 
      post    :vote
      post    :favorite
      patch   :unfavorite  #FIXME patch instead of delete? actually...don't need route??
    end
  end

  scope :discussion do 
    resources :posts do
      resources :comments do
      end
    end
    get '/yelp' => 'posts#search', as: 'search_yelp'
  end

  resources :schedule
  resources :availabilities
  resources :budget , only: [:index, :create, :destroy]

  patch '/budget/update' => 'budget#update', as: 'udpate_budget'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to  :user
  has_many    :comments, dependent: :destroy

  validates   :title, presence: true
  validates   :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Yelp::V2::Search::Request

  def index
    @posts = Post.all
  end

  def new
    if params[:post]
      @post=Post.new post_params 
    else
      @post= Post.new
    end 
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def search
    client = Yelp::Client.new
    request = Location.new(
               :term => params[:term],
               :category_filter => params[:category_filter],
               :limit => 10,
               :radius_filter => 8047,
               :city => params[:city],
               :state => params[:state])
               #:latitude => 38.854082, #params[:latitude],
               #:longitude =>  -77.048884) #params[:longitude])
    response = client.search(request)
    @result = response["businesses"]
    #render json: { results: [] }
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
      #params.permit("title", "body")
    end

  end

app/views/posts/edit.html.erb
<div class="container">
<h2>Editing your posting below:</h2>
 
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<%= link_to 'Back', posts_path %>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="container" >
  <%= link_to new_post_path do %><h2>
    <i class="fa fa-pencil-square"></i> Have something to add?
  </h2><% end %>
</div>

<br>

<div class="container">
  
  <div class="row">
    <div class="col-md-8">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr> 
            <th><h4><strong> Subject </strong></h4></th>
            <th><h4><strong> Date-Time Posted EST</strong></h4></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |p| %>
            <tr>
              <td><%= link_to p.title, post_path(p) %> </td>
              <td><%= p.created_at %> </td>
            
              <td><%= link_to edit_post_path(p) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              </td>
              <td><%= link_to post_path(p), method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <div>
        <%= form_tag search_yelp_path, action: "search", method: "get" do %>
          <%# label :term #put in placeholder styling  %>
          <%= text_field_tag :term, nil, placeholder: 'e.g. restaurant, food' %><br>
          <%# label :category_filter #put in placeholder styling %>
          <%= text_field_tag :category_filter, nil, placeholder: 'e.g. thai, korean'%><br>
          <%= text_field_tag :city, nil, placeholder: 'e.g. Arlington'%>
          <%= text_field_tag :state, nil, placeholder: 'e.g. VA'%><br>
          <!-- <i class="fa fa-yelp"></i> -->
        <button>Search Yelp for Ideas</button>
        <% end %>
        <div id="yelp_search_results"></div>
      </div>
    </div>
  
  </div>
</div>


<script type="application/javascript">
  var add_search_results = function(response) {
    console.log(response);
    var yelpHTML = '<ul class="bulleted">';
    $.each(response, function (index, result){
      yelpHTML += '<li>'+ '<a href="/discussion/posts/new?post[title]=' + result.name + '">' + result.name + '</a>' +" "+result.address[0]+", "+result.address[1]+'</li>';
    });
    yelpHTML += '</ul>';
    $('#yelp_search_results').html("");
    $('#yelp_search_results').append(yelpHTML);
  };

  $(document).ready(function() {
    $('form').submit(function(e) {
      e.preventDefault();
      var url = $(this).attr("action");
      var formData = $(this).serialize();
      $.ajax(url, {
        data : formData,
        type: "GET",
        success: add_search_results
      });
    });
  });
</script>

app/views/posts/new.html.erb
<div class="container">
<h2> It's all in the details...</h2><br>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @post do |f| %> 
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <button>Post</button>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="container">
<h2>These are my thoughts.. what are yours?</h2>

<div class="container">
<p> 
<strong>Subject:</strong>
<%= @post.title %>
</p>
<p>
<strong>Body:</strong>
<%= @post.body %>
</p>
</div>

<div class="container">
<% @post.comments.each do |c| %>
  <p>
    <strong>Commenter:</strong>
    <%= c.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= c.blurb %>
  </p>
<% end %>
</div>

<div class="container">
<h2>Add a comment: </h2>
<%= form_for [@post, @post.comments.build] do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :blurb %><br>
    <%= f.text_area :blurb %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<div class="container">

<%= link_to 'Back', posts_path %> 
<%= link_to 'Edit', edit_post_path(@post) %>
</div>