config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'application#home'

  resources :profile

  resources :dress do 
    member do 
      post    :vote
      post    :favorite
      patch   :unfavorite  #FIXME patch instead of delete? actually...don't need route??
    end
  end

  scope :discussion do 
    resources :posts do
      resources :comments do
      end
    end
    get '/yelp' => 'posts#search', as: 'search_yelp'
  end

  resources :schedule
  resources :availabilities
  resources :budget , only: [:index, :create, :destroy]

  patch '/budget/update' => 'budget#update', as: 'udpate_budget'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class name
    # Translate rails conventions to bootstrap conventions
    case name.to_sym
    when :notice
      :success
    when :alert
      :danger
    else
      name
    end
  end

end

app/views/application/home.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active first-slide">
      <!--<img class="first-slide" src="/ceremony.jpg" alt="First slide">-->
      <div class="container">
        <div class="carousel-caption">
          <h1>Let's pick a dress!</h1>
          <p>The most important thing after the ring.</p>
          <p><%= button_to "Vote Now", new_dress_path, method: :get, class: "btn btn-lg btn-primary" %></p>
        </div>
      </div>
    </div>
    <div class="item second-slide">
      <!-- <img class="second-slide" src="/pj.jpg" alt="Second slide"> -->
      <div class="container">
        <div class="carousel-caption">
          <h1>What do you have in mind?</h1>
          <p>It's all in the details.</p>
          <p><%= button_to "Start Planning", posts_path, method: :get, class: "btn btn-lg btn-primary" %></p>
        </div>
      </div>
    </div>
    <div class="item third-slide">
      <!-- <img class="third-slide" src="/linz.jpg" alt="Third slide"> -->
      <div class="container">
        <div class="carousel-caption">
          <h1>What's your schedule like?</h1>
          <p>Glad you asked. I'm available...</p>
          <p><%= button_to "View Calendar", schedule_index_path, method: :get, class: "btn btn-lg btn-primary" %></p>
        </div>
      </div>
    </div>
    <div class="item fourth-slide">
      <!-- <img class="fourth-slide" src="/332.jpg" alt="Fourth slide"> -->
      <div class="container">
        <div class="carousel-caption">
          <h1>What's your budget?</h1>
          <p>Let's talk money.</p>
          <p><%= button_to "$$$", budget_index_path, method: :get, class: "btn btn-lg btn-primary" %></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->


<!-- START THE FEATURETTES -->
<div class="container features">
<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">The perfect dress. <br><span class="text-muted">Narrow down the choices.</span></h2>
    <p>Suggest bridesmaid dresses by uploading your pictures or links, then vote on your top choices. Remember, the bride gets the final say. She will mark her favorites.</p>
      <p><%= link_to new_dress_path do %>
        <i class="fa fa-female"></i> Make Suggestions
      <% end %>
      </p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive center-block" src="/dress.jpg" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 col-md-push-5">
    <h2 class="featurette-heading">Let's discuss. <br><span class="text-muted">Multiple ideas at once.</span></h2>
    <p>No more sifting through emails and text messages to find the latest communications. Easily find topics in the discussion forum and add your comments. Get ideas using the yelp search box without leaving the discussion.</p>
      <p><%= link_to posts_path do %>
        <i class="fa fa-glass"></i> Start Planning
      <% end %></p>
  </div>
  <div class="col-md-5 col-md-pull-7">
    <img class="featurette-image img-responsive center-block" src="/cake.jpg" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Scheduling. <br><span class="text-muted">Who? What? When? Where? </span></h2>
    <p>We all lead busy lives. It's difficult to keep track of your own schedule, let alone others'. Coordinate schedules with ease in one spot.</p>
      <p><%= link_to schedule_index_path do %>
        <i class="fa fa-calendar"></i> Mark the Calendar
      <% end %></p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive center-block" src="/calendar.jpg" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 col-md-push-5">
    <h2 class="featurette-heading">Set a budget. <br><span class="text-muted">Track your expenses.</span></h2>
    <p>Keep tabs on the bachelorette bash and bridal shower. And more!</p>
    <p><%= link_to budget_index_path do %>
        <i class="fa fa-credit-card"></i> Update Expenses
      <% end %></p>
  </div>
  <div class="col-md-5 col-md-pull-7">
    <img class="featurette-image img-responsive center-block" src="/camping.jpg" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2015 EmilyChu, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

</div><!-- /.container -->